app/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.login, name='login'),
    path('dept-list/', views.DepartmentView, name='department_view'),
    path('dept-list/<slug:slug>/', views.CoursesView.as_view(), name='courses'),
    path('dept-list/<slug:slug>/save_course', views.SaveCourse, name='save_course'),
    path('dept-list/<slug:slug>/save_schedule', views.SaveCourseInSchedule, name = 'save_schedule'),
    
    path('profile/', views.ProfileView, name='profile_view'),
    path('profile/<slug:slug>/save_schedule2', views.SaveCourseInSchedule, name = 'save_schedule2'),
    path('profile/delete_save', views.DeleteCourse, name = 'delete_save'),
    path('profile/delete_schedule', views.DeleteScheduledCourse, name='delete_schedule'),
    path('profile/save_friend', views.SaveFriend, name='save_friend'),
    path('profile/delete_friend', views.DeleteFriend, name='delete_friend'),
    path('profile/search_friend', views.SearchFriendView, name='search_friend'),
    
    path('saved-courses/', views.SavedCoursesView, name='saved_courses_view'),
    path('saved-courses/delete_save', views.DeleteCourse, name = 'delete_save2'),
    path('saved-courses/<slug:slug>/save_schedule3', views.SaveCourseInSchedule, name = 'save_schedule3'),
    
    path('sched-courses/', views.ScheduledCoursesView, name='sched_courses_view'),
    path('sched-courses/delete_schedule',  views.DeleteScheduledCourse, name='delete_schedule2'),
   
    path('saved-friends/', views.SavedFriendsView, name='saved_friends_view'),
    path('saved-friends/delete_friend', views.DeleteFriend, name='delete_friend2'),
    path('saved-friends/<str:owner>', views.FriendView, name='friend_view'),
    path('saved-friends/<str:owner>/add_comment', views.AddComment, name='add_comment'),
    path('saved-friends/<str:owner>/del_comment', views.DeleteComment, name='del_comment'),

    path('search_view/', views.SearchView, name='search_view'),
    path('search_view/save_course', views.SearchSaveCourse, name='search_save_course'),
    path('search_view/save_schedule', views.SearchSaveCourseInSchedule, name = 'search_save_schedule'),
    path('user-settings', views.userSettings, name='user-settings'),
    path('user-settings-update', views.userSettingsUpdate, name='user-settings-update'),
    
]
    
    
    

louslist/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('allauth.urls')),
    
]
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

app/models.py
from django.db import models
from django.conf import settings
from django.views.generic.detail import DetailView
from django.contrib.auth.models import User, AnonymousUser
from django.dispatch import receiver
from django.db.models.signals import post_save

class Department(models.Model):
    """
    Model that describes a whole department.
    """
    slug = models.SlugField(max_length=10, null=True)
    
    def __str__(self):
        return self.slug
    def first_letter(self):
        return self.slug and self.slug[0] or ''
    
class Course(models.Model):
    """
    Model that visualizes a specific course in a department.

    """
    #Key to link a course to a department
    department_ptr = models.ForeignKey(Department,on_delete=models.CASCADE, null=True)
    dept_slug = models.CharField(max_length=15, null=True)

    # Instructor Logistics
    instructor_name = models.CharField(max_length=120, null=True)
    instructor_email = models.CharField(max_length=60, null=True)
    
    
    # Course Logistics
    course_num = models.CharField(max_length=20, null=True)
    semester_code = models.CharField(max_length=20, null=True)
    section = models.CharField(max_length=20, null=True)
    subject = models.CharField(max_length=20, null=True)
    course_cat = models.CharField(max_length=20, null=True)
    course_name = models.CharField(max_length=1200, null=True)
    units  = models.CharField(max_length=20, null=True)
    component = models.CharField(max_length=20, null=True)
    capacity = models.CharField(max_length=20, null=True)
    wait_list = models.CharField(max_length=20, null=True)
    wait_cap = models.CharField(max_length=20, null=True)
    enrollment_total = models.CharField(max_length=20, null=True)
    enrollment_available = models.CharField(max_length=20, null=True)
    topic = models.CharField(max_length=100, null=True)
    
    location = models.CharField(max_length=70, null=True)
    
    # Course Timing Logistics
    meeting_days = models.CharField(max_length=20, null=True)
    start_time = models.CharField(max_length=30, null=True)
    end_time = models.CharField(max_length=30, null=True)
    
    def __str__(self):
        # EX: CS1110 -- 001: Introduction to Programming
        return self.subject + self.course_cat + " -- " + self.section + ": " + self.course_name
    

class Comment(models.Model):
    """
    Model that defines a comment on a user's schedule page.
    """
    comment = models.CharField(max_length=1000)
    date = models.DateTimeField(auto_now_add=True, blank=True)
    author = models.CharField(max_length=100, null = True)

    def __str__(self):
        return self.comment

class UserProfile(models.Model):
    """
    Separate model that extends the Django User model using a 1-to-1 key.
    It has additional fields to keep track of courses, friends, comments, and much more.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank =True)
    scheduled_courses = models.ManyToManyField(Course, related_name='user_schedule')
    saved_courses = models.ManyToManyField(Course)
    friends = models.ManyToManyField(User, related_name='friends')
    comments_sent = models.ManyToManyField(Comment, related_name='comments_sent')
    comments_received = models.ManyToManyField(Comment, related_name='comments_received')

    major = models.CharField(max_length=60, null=True)
    year = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.user.username


# this receiver detects whenever a user is created with the default django User model
# and creates a UserProfile associated with that user
@receiver(post_save, sender = User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

    
    


    

app/templates/app.html
{% extends 'navbar_footer.html' %}
<!-- CSS only -->

{% load static %}
{% block content %}
<div class="container back3 position-sticky">
  <div class="row"><div class="col">

    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
     
      <div {% if message.tags %}class="alert {{message.tags}} alert-dismissible fade show" {% endif %}role="alert" id = "succalert">
        {{ message }}
        <button  type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        
      </div>
      <script type="text/javascript">
        setTimeout(function () {
  
            // Closing the alert
            $('#succalert').alert('close');
        }, 1000);
    </script>
      {% endfor %}
    </ul>
    {% endif %}

  </div></div>

</div>
<div class="row"><div class="col">
  
  
  
    {% if user.is_authenticated %}
    
    <div class="container">
    <div class="row home align-items-center" style= "height: 500px">
        <h1 align ="center">Hooz List</h1>

        <p align = "center" >You are now signed in as {{ user.email }}</p>
        
        <div class="d-grid gap-2 col-6 mx-auto">
          <a class="btn btn-lg btn-dark" href="{% url 'department_view' %}" role="button">
            View Course Catalog
          </a>
        </div>
        <p align = "center" ><a href="{% url 'account_logout' %}">Sign Out</a></p>
        
    </div> 
  </div>
    {% else %}
   
        

         <div class="container-fluid text-end" >

            <div class="row align-items-center" style="height: 775px">
                

                <div class="col-10 align-self-center" style = "height: 150px">
                  <h1 class="home1">
                    HoozList
                  </h1>
                  <a class="btn btn-lg btn-dark" href="{% url 'account_login' %}" >Log In To Get Started</a>
                </div>
                <div class="col-2"></div>
              </div>
            
            
            
    
        </div>
      
    {% endif %}


    {% endblock %}

app/templates/course_schedule_error.html
{% extends 'navbar_footer.html' %}
{% load static %}
{% block content %}

<div class="container courselist">

    <div class="row">

        <div class="row">

            <h1>Error adding {{selected_course.dept_slug}} {{selected_course.course_cat}} to {{user2.first_name}} schedule.
                {{conflicted_course.dept_slug}} {{conflicted_course.course_cat}} conflicted in times in current schedule.
            </h1>

        </div>

    </div>


</div>

{% endblock %}

app/templates/course_view.html
{% extends 'navbar_footer.html' %}
{% load static %}
{% block content %}
<!-- Courses --
<div class="text-center courselist">
<h1>{{ department.slug }}</h1>
<ul class = "list-unstyled">

<div class="course">
    <li><b>{{course.subject}}{{ course.course_cat }}-{{course.section}}:</b> {{course.course_name}}</li>
    <li>{{course.component}} - ({{course.units}} Units) | {{course.enrollment_total}} / {{course.capacity}}</li>
    <li>{{course.instructor_name}} --- {{course.meeting_days}} {{course.start_time}}-{{course.end_time}}  </li>
</div>

</ul>

</div>
<!-End Courses -->
<style>
    .back2 {
    border: 0.1rem solid rgba(0, 0, 0, 0); 
    background-color: rgb(30, 35, 40);
    border-radius: 0.5rem;
    padding: 0.1rem;
    max-width: 1685px;
    text-align: center;
    align-items: center;
    
    margin-top: 10px;
    margin-bottom: 0px;
    padding: 1rem;  
    opacity: 1;
    color: white;
    font-weight: bold;
    font-size: 40px;
}
.back3 {
    
    background-color: rgba(30, 35, 40, 0);
    
    padding: 0.1rem;
    max-width: 1685px;
    text-align: center;
    align-items: center;
    
    margin-top: 100px;
    margin-bottom: 0px;
    padding: 1rem;  
    
}
.close{
  border: 1px solid rgba(0, 0, 0, 0.12);
  background-color: rgba(172, 164, 164, 0);
  padding-top: 1px;
  
}
</style>

<!--{% if success == True %}
  <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 1rem;">
    <strong>{{msg}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %} -->
  <div class="container back3">
    <div class="row"><div class="col">

      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
       
        <div {% if message.tags %}class="alert {{message.tags}} alert-dismissible fade show" {% endif %}role="alert" id="succalert" style="margin-top: 1rem;">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <script type="text/javascript">
          setTimeout(function () {
    
              // Closing the alert
              $('#succalert').alert('close');
          }, 3000);
      </script>
        {% endfor %}
      </ul>
      {% endif %}
  
    </div></div>
  </div>
<div class="container back2">
  
    <div class="row header">
        <div class="col">
         {{department.slug}}
        </div>
    </div>
</div>
<div class="container-fluid" style="max-width: 1700px; margin-top: 0rem;
margin-bottom: 10rem;">
<table class="table table-striped table-hover table-secondary table-bordered">
    <thead class="table-dark ">
      <tr class="">
        <th scope="col">Section</th>
        <th scope="col">Course Code</th>
        <th scope="col">Course Name</th>
        <th scope="col">Instructor</th>
        <th scope="col">Meeting Date/Time</th>
        <th scope="col">Location</th>
        <th scope="col">Units</th>
        <th scope="col">Waitlist Available</th>
        <th scope="col">Enrollment Available</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
        {% for course in department.course_set.all %}
        <tr>
        <th >{{course.section}}</th>
        <td>{{course.subject}} {{ course.course_cat }}</td>
        <td>{{course.course_name}}</td>
        <td>{{course.instructor_name}}</td>
        <td>{{course.meeting_days}}: {{course.start_time}}-{{course.end_time}}</td>
        <td>{{course.location}}</td>
        <td>{{course.units}}</td>
        <td>{{course.wait_list}}/{{course.wait_cap}}</td>
        <td>{{course.enrollment_available}}/{{course.capacity}}</td>
        <td>
            <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              More
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li>
                    <!-- need to use this form block to generate the post data -->
                    <!-- action sends the data to urls.py and method indicates that it's supposed to send data, not receive -->
                    <!--urls.py then calls the appropriate view to execute the logic-->
                    <form action="{% url 'save_course' department.slug %}" method="post">
                    {% csrf_token %}
                    <!--this sends back whatever is in name and value-->
                    <button class="dropdown-item" type  = "submit" name="course_choice" id="course_choice" value="{{course.id}}" >Save Course</button>
                    </form>
                </li>
              <li>
                <form action="{% url 'save_schedule' department.slug %}" method="post">
                  {% csrf_token %}
                  <button class="dropdown-item" type = "submit" name = "course_choice" id="course_choice" value="{{course.id}}">Add to Schedule</button>
                </form>
                
              </li>
            </ul>
          </div>
        </td>
        
      </tr>
      {% endfor %}
    </tbody>
  </table>
  
</div>


{% endblock %}

app/templates/delete_friend.html
{% extends 'navbar_footer.html' %}
{% load static %}
{% block content %}

<div class="container courselist">

    <div class="row">

        <div class="row">

            <h1>{{friend.username}} was successfully deleted</h1>

        </div>

    </div>


</div>

{% endblock %}

app/templates/department_view.html
{% extends 'navbar_footer.html' %}
{% load static %}
{% block content %}
<style>
.header{
  border: 0.1rem solid black; 
    background-color: rgb(30, 35, 40);
    border-radius: 0.5rem;
    
    max-width: 50rem;
    text-align: center;
    align-items: center;
    font-weight: bolder; 
    font-size:50px;
    color: white;
    padding: 1rem;  
    


}
.deptButton{
  border: 0.0rem solid rgb(255, 255, 255);
  background-color: rgb(197, 196, 196);
  border-radius: 0.0rem;
  color: white;
  padding: 1rem;  
  
  opacity: 1;
}
.back {
    border: 0.1rem solid rgba(0, 0, 0, 0); 
    background-color: rgba(255, 255, 255, 0);
    border-radius: 0.5rem;
    padding: 0.1rem;
    max-width: 50rem;
    text-align: center;
    align-items: center;
    margin: auto;
    margin-top: 10rem;
    margin-bottom: 10rem;
    padding: 1rem;  
    opacity: 1;
}

</style>

<div class="container back text-center">
  {% if user.is_authenticated %}
  <div class="row header">
    <div class="col align-self-center" >Departments List</div>
  </div>
  
  <div class="row"><div class="col">
    <div class="accordion deptButton" id="accordionExample">
      {% regroup department by first_letter as letter_list %}
      {% for letter in letter_list %}
      
      <div class="accordion-item">
        <h2 class="accordion-header font-weight-bold" id="heading{{letter.grouper }}" style="text-align: center">
          <button class="accordion-button  collapsed btn btn-dark  d-block text-center" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{letter.grouper}}" aria-expanded="true" aria-controls="collapse{{letter.grouper}}">
            {{ letter.grouper }}
          </button>
        </h2>
        <div id="collapse{{letter.grouper}}" class="accordion-collapse collapse" aria-labelledby="heading{{letter.grouper}}" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <ul class = "list-unstyled">
              {% for item in letter.list %}
              <li>
              <a class="btn btn-dark" style= "width: 150px;"href="{% url 'courses' item.slug %}" role="button">
                {{ item.slug }}
              </a>
            </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div></div>
  {% else%}
  <div class="row header">
    <div class="col align-self-center" >Please sign in to see the course catalog!</div>
  </div>
  <div class="row deptButton">
    <div class="col align-self-center" ><a class="btn btn-lg btn-dark" href="{% url 'account_login' %}" >Sign In</a>
    </div>
  </div>
  {% endif %}
</div>


{% endblock %}

app/templates/error.html
{% extends 'navbar_footer.html' %}
{% load static %}
{% block content %}

<div class="container courselist">

    <div class="row">

        <div class="row">

            <h1>There was an error with that operation. Please try again later.</h1>

        </div>

    </div>


</div>

{% endblock %}

app/templates/friend_courses.html
{% extends 'navbar_footer.html' %}
{% load static %}
{% block content %}
<style>
    .back3 {
    
    background-color: rgba(30, 35, 40, 0);
    
    padding: 0.1rem;
    max-width: 1685px;
    text-align: center;
    align-items: center;
    
    margin-top: 100px;
    margin-bottom: 0px;
    padding: 1rem;  
    
}
</style>
<div class="container back3 position-sticky">
    <div class="row"><div class="col">
  
      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
       
        <div {% if message.tags %}class="alert {{message.tags}} alert-dismissible fade show" {% endif %}role="alert" id = "succalert">
          {{ message }}
          <button  type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          
        </div>
        <script type="text/javascript">
          setTimeout(function () {
    
              // Closing the alert
              $('#succalert').alert('close');
          }, 3000);
      </script>
        {% endfor %}
      </ul>
      {% endif %}
  
    </div></div>
  
  </div>
  
<div class="container courselist">
    <h2>Here is your friend's schedule</h2>
    
    <div class="row">

        <div class="col">
            {% if scheduled_courses_list %}
            <table class="table table-striped table-hover table-secondary table-bordered">
                <thead class="table-dark ">
                  <tr class="">
                    <th scope="col">Section</th>
                    <th scope="col">Course Code</th>
                    <th scope="col">Course Name</th>
                    <th scope="col">Instructor</th>
                    <th scope="col">Meeting Date/Time</th>
                    <th scope="col">Location</th>
                  </tr>
                </thead>
                <tbody>
                    {% for course in scheduled_courses_list %}
                    <tr>
                    <th >{{course.section}}</th>
                    <td>{{course.subject}} {{ course.course_cat }}</td>
                    <td>{{course.course_name}}</td>
                    <td>{{course.instructor_name}}</td>
                    <td>{{course.meeting_days}}: {{course.start_time}}-{{course.end_time}}</td>
                    <td>{{course.location}}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              {% else %}
              <p1>
                They currently have no courses :(
              </p1>
              {% endif %}
        </div>
    
    </div>
    <div style="text-align:left">
      <h3> Add your comments here! </h3>
      <form action="{% url 'add_comment' owner=friend.username%}" method="post">
          {% csrf_token %}
          <textarea cols="70" rows="1" name="comment"></textarea><br><br>
          <input type="submit" value="Submit" class="btn btn-dark">
      </form>
                      
  </div>
  <h2 style="text-align:left">Comments:</h2>
    <div class="row"><div class="col">
      {% if comments_received %}
      {% for comment in comments_received %}
      <div class="card p-3">
    
        <div class="d-flex justify-content-between align-items-center">
    
      <div class="user d-flex flex-row align-items-center">
    
        <img src="https://i.imgur.com/WUGxiYh.jpeg" width="30" class="user-img rounded-circle mr-2">
        <span><small class="font-weight-bold text-primary">{{comment.author}}</small> <small class="font-weight-bold">{{comment.comment}}</small></span>
          
      </div>
    
    
      <small>{{comment.date}}</small>
    
      </div>
    
    
      <div class="action d-flex justify-content-between mt-2 align-items-center">
    
        <div class="reply px-4">
            {% if comment.author == user.username %}
            <small><form action="{% url 'del_comment' owner=friend.username %}" method="post">
              {% csrf_token %}
              <button class="btn btn-secondary btn-dark btn-sm" type  = "submit"  name="comment_choice" id="comment_choice" value="{{comment.id}}" >Delete Comment</button>
            </form></small>
            {% endif %} 
           
        </div>
    
        
      </div>
    
      
        
      </div>
      {% endfor %}
      {% else %}
        <p1>There are no comments :(</p1><br>
        <br>
      
        {%endif%}


    </div></div>




</div>




{% endblock %}

app/templates/saved_courses.html
{% extends 'navbar_footer.html' %}

{% block content %}
<style>
    .back3 {
    
    background-color: rgba(30, 35, 40, 0);
    
    padding: 0.1rem;
    max-width: 1685px;
    text-align: center;
    align-items: center;
    
    margin-top: 100px;
    margin-bottom: 0px;
    padding: 1rem;  
    
}
</style>
<div class="container back3 position-sticky">
    <div class="row"><div class="col">
  
      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
       
        <div {% if message.tags %}class="alert {{message.tags}} alert-dismissible fade show" {% endif %}role="alert" id = "succalert">
          {{ message }}
          <button  type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          
        </div>
        <script type="text/javascript">
          setTimeout(function () {
    
              // Closing the alert
              $('#succalert').alert('close');
          }, 3000);
      </script>
        {% endfor %}
      </ul>
      {% endif %}
  
    </div></div>
  
  </div>
  
<div class="container-fluid courselist" style="max-width: 1700px;">
    <h2>Here are your saved courses</h2>
    <div class="row">

        <div class="col">
            {% if saved_courses_list %}
            <table class="table table-striped table-hover table-secondary table-bordered">
                <thead class="table-dark ">
                  <tr class="">
                    <th scope="col">Section</th>
                    <th scope="col">Course Code</th>
                    <th scope="col">Course Name</th>
                    <th scope="col">Instructor</th>
                    <th scope="col">Meeting Date/Time</th>
                    <th scope="col">Location</th>
                    <th scope="col">Units</th>
                    <th scope="col">Waitlist Available</th>
                    <th scope="col">Enrollment Available</th>
                    <th scope="col">Actions</th>
                  </tr>
                </thead>
                <tbody>
                    {% for course in saved_courses_list %}
                    <tr>
                    <th >{{course.section}}</th>
                    <td>{{course.subject}} {{ course.course_cat }}</td>
                    <td>{{course.course_name}}</td>
                    <td>{{course.instructor_name}}</td>
                    <td>{{course.meeting_days}}: {{course.start_time}}-{{course.end_time}}</td>
                    <td>{{course.location}}</td>
                    <td>{{course.units}}</td>
        <td>{{course.wait_list}}/{{course.wait_cap}}</td>
        <td>{{course.enrollment_available}}/{{course.capacity}}</td>
        
                    <td>
                        <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                          More
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <li>
                                <!-- need to use this form block to generate the post data -->
                                <!-- action sends the data to urls.py and method indicates that it's supposed to send data, not receive -->
                                <!--urls.py then calls the appropriate view to execute the logic-->
                                <form action="{% url 'delete_save2' %}" method="post">
                                  {% csrf_token %}
                                  <button class="btn" type  = "submit"  name="course_choice" id="course_choice" value="{{course.id}}" >Delete Course</button>
                                </form>
                            </li>
                          <li>
                            <form action="{% url 'save_schedule3' course.dept_slug%}" method="post">
                              {% csrf_token %}
                              <button class="dropdown-item" type = "submit" name = "course_choice" id="course_choice" value="{{course.id}}">Add to Schedule</button>
                            </form>
                            
                          </li>
                        </ul>
                      </div>
                    </td>
                    
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              {% else %}
              <p1>
                You have no saved courses
              </p1>
              {% endif %}
        </div>

    </div>


</div>

{% endblock %}

app/templates/saved_friends.html
{% extends 'navbar_footer.html' %}
{% load static %}
{% block content %}
<style>
    .back3 {
    
    background-color: rgba(30, 35, 40, 0);
    
    padding: 0.1rem;
    max-width: 1685px;
    text-align: center;
    align-items: center;
    
    margin-top: 100px;
    margin-bottom: 0px;
    padding: 1rem;  
    
}
</style>
<div class="container back3 position-sticky">
    <div class="row"><div class="col">
  
      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
       
        <div {% if message.tags %}class="alert {{message.tags}} alert-dismissible fade show" {% endif %}role="alert" id = "succalert">
          {{ message }}
          <button  type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          
        </div>
        <script type="text/javascript">
          setTimeout(function () {
    
              // Closing the alert
              $('#succalert').alert('close');
          }, 3000);
      </script>
        {% endfor %}
      </ul>
      {% endif %}
  
    </div></div>
  
  </div>
  
<div class="container courselist">

    
<div class="row">
    <div class="col">
        <h2>Here are your friends</h2>
        {% if friends_list %}
        

          <!--

            
          -->
          <div class="container-fluid" style="max-width: 1700px; margin-top: 0rem;
margin-bottom: 10rem;">
<table class="table table-striped table-hover table-secondary table-bordered">
    <thead class="table-dark ">
      <tr class="">
        <th scope="col">Name</th>
        <th scope="col">Username</th>
        <th scope="col">Email</th>
        <th scope="col">Actions</th>
        
      </tr>
    </thead>
    <tbody>
      {% for friend in friends_list %}
        <tr>
        <td >{{friend.first_name}}</td>
        <td>{{friend.username}}</td>
        <td>{{friend.email}}</td>
        <td>
            <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              More
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li>
                  <form action="{% url 'delete_friend2' %}" method="post">
                  {% csrf_token %}
                  <button class="dropdown-item" type="submit"  name="friend_choice" id="friend_choice" value="{{friend.id}}" >Delete Friend</button>
                </form>
                
                </li>
              <li>
                <a href='/saved-friends/{{friend.username}}' class='dropdown-item'> View Schedule </a>
              
                
              </li>
            </ul>
          </div>
        </td>
        
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
          <p1>
            You have no friends :(
          </p1>
          {% endif%}
</div>
<div class="row">

  <div class="col-8">
      <h3>Search for friends here (enter email)</h3>
      <form class="d-flex" method="POST" action="{% url 'search_friend'%}">
          {%csrf_token%}
          <input class="form-control me-2" style= "width:170px" type="search" placeholder="Find Friends..." aria-label="Search" name = "searched">
          <button class="btn btn-dark btn-sm"  type="submit">Search</button>
        </form>

  </div>

</div>

 <!---->
 {% if friends %}
 <div class="container-fluid" style="max-width: 1700px; margin-top: 0rem;
 margin-bottom: 10rem;">
 <table class="table table-striped table-hover table-secondary table-bordered">
     <thead class="table-dark ">
       <tr class="">
         <th scope="col">Name</th>
         <th scope="col">Username</th>
         <th scope="col">Email</th>
         <th scope="col">Action</th>
         
       </tr>
     </thead>
     <tbody>
       {% for friend in friends%}
         <tr>
         <td >{{friend.first_name}}</td>
         <td>{{friend.username}}</td>
         <td>{{friend.email}}</td>
         <td>
          <form action="{% url 'save_friend' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-secondary btn-dark" type  = "submit"  name="friend_choice" id="friend_choice" value="{{friend.id}}" >Save Friend</button>
          </form>
         </td>
         
       </tr>
       {% endfor %}
     </tbody>
   </table>
  

   {%endif%}
 </div>
 <!---->


</div>

</div>


         
    </div>
</div>

</div>

{% endblock %}